// This file is automatically generated by refresh-create-templates.ts.
// Do not edit manually. Or do, I'm a comment, not a cop.

export interface Template {
	repo: string
	name: string
	description: string
	shortDescription?: string
	order?: number
}

export const TEMPLATES: Template[] = [
	{
		name: 'Agent',
		description: 'Work on the canvas with an AI agent.',
		shortDescription: 'An AI-powered agent.',
		order: 1,
		repo: 'tldraw/agent-template',
	},
]
